version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
    volumes:
      - /home/schuah/data/wordpress:/var/www/html
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    restart:  always
    volumes:
      - /home/schuah/data/wordpress:/var/www/html
    networks:
      - network

volumes:
  wp_website:
    driver: local
    driver_opts:
      type: none
      device: /home/schuah/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
