version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: always
    volumes:
      - /home/schuah/data/wordpress:/var/www/html
    networks:
      - network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - /home/schuah/data/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/schuah/data/mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - network

volumes:
  wp_website:
    driver: local
    driver_opts:
      type: none
      device: /home/schuah/data/wordpress
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/schuah/data/mysql
      o: bind

networks:
  network:
    driver: bridge
